enum constants {
  CHANGE_MD_INPUT_VALUE = 'CHANGE_MD_INPUT_VALUE',
  CHANGE_CUSTOM_STYLE_VISIBLE = 'CHANGE_CUSTOM_STYLE_VISIBLE',
  CHANGE_CODE_THEME = 'CHANGE_CODE_THEME',
  CHANGE_CONTENT_THEME = 'CHANGE_CONTENT_THEME'
}

export default constants;
